### PR TITLE
refactor docker run to work with latest jujubox

### PR DESCRIPTION
**Pull request by kwmonroe**
The latest jujubox now uses ENTRYPOINT instead of CMD ./run.sh. CWR
needs to override this entrypoint to issue its commands. Otherwise,
it will sit in an interactive shell forever.

Move to jujusolutions/cwrbox to round out this commit.

### CODE REVIEW

**Comment by seman** [comment]
Let me know once this is tested.

**Comment by kwmonroe** [comment]
I tested this against Azure just a few minutes ago.  The parts affected by this PR worked (`jujusolutions/cwrbox`, setting the `--entrypoint` arg, and constructing the `docker run` command):

http://paste.ubuntu.com/23564743/

Note there is still an issue with cwr, but that seems unrelated to me, and is raised here:

https://github.com/juju-solutions/cloud-weather-report/issues/85

**Comment by seman** [comment]
Thanks. 
This update might break the unit tests. Please make sure `make test` passes without error.

**Comment by kwmonroe** [comment]
Good catch @seman -- i forgot to update the unit test for the updated function.  That's done now; `make test` runs without error.

**Comment by johnsca** [comment]
I tested this also and it has my +1

**Pull request merged**
